### ISSUE TITLE
bug: backslashes are not escaped

### ISSUE THREAD

**Issue by dhakehurst** [ExposedCat/rollup-plugin-string-import#1]
Hi,
Nice plugin, thanks.

I have a problem importing a text file that contains some backslash '\' characters.

They to do not get escaped, i.e. converted to '\\' when converted to a javascript string.

I would have expected a "true" conversion from the text file that handles escaping any special characters,
so that the resulting string is a true representation of the string in the file.

Am I missing something in the configuration ?

**Comment by ExposedCat** [comment]
@dhakehurst hi, thanks for the report. Nope, you don't miss anything - it should work out of the box.

Could you please try version `1.2.5` from npm or provide an example file content you have issue with?

**Comment by dhakehurst** [comment]
I worked around the issue by adding this to the config
`transform: (content, file) => content.replaceAll("\\","\\\\")`

**Comment by dhakehurst** [comment]
version 1.2.5 seems to work without the explicit transformation,

thanks

**Comment by ExposedCat** [comment]
Fixed in `1.2.5`, thanks @dhakehurst for the report
